### ISSUE TITLE
Content provided to filter isn’t text

### ISSUE THREAD

**Issue by kbreit** [clay584/parse_genie#7]
I am running a basic `show version` command and am having problems executing the filter. The filter is giving me this error:

“The content provided to the parse_genie filter was not a string.”

I’m executing this...

```
nxos_command:
  command: show version
register: version

set_fact:
  pyats_version: ‘{{ version[“stdout”][0] | parse_genie(command=“show version”, os=“nxos”) }}’
```
